blank_issues_enabled: false
contact_links:
  - name: Telegram Official Group
    url: https://t.me/aospb_chat
    about: Join our official group for any queries related to aosPB-Project.
  - name: Telegram Official Channel
    url: https://t.me/aospb_releases
    about: Join our official channel to get the latest updates.
